### ISSUE TITLE
Together AI Llama-3.1-405B "Credit limit exceeded" Issue

### ISSUE THREAD

**Issue by KirillUtyashev** [expectedparrot/edsl#2098]
Hi!

I’m encountering an unexpected issue when running experiments using Together AI’s LLaMA 3.1-405B model through EDSL. Specifically, I receive the following error:

> {'message': "Error code: 402 - {'id': 'o3LiXw4-62bZhn-96040daf687810ab', 'error': {'message': 'Credit limit exceeded. Please navigate to https://api.together.xyz/settings/billing to add credit or upgrade your plan.', 'type': 'credit_limit', 'param': None, 'code': None}}"}
> 

However:

- When I query the same model directly via Together AI’s API SDK, using the same prompts, everything works as expected.

- I verified the prompts using the `show_prompts()` method in EDSL and confirmed they work correctly when used directly with Together AI’s inference.

- For reference, here are the relevant code snippets from my setup:

```
model_llama = Model('meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo', temperature=0, logprobs=True)
model_llama.tpm = 250000
model_llama.rpm = 1800

```

```
for s in sl:
    job = q.by(s)
    a = Agent(...)
    r = job.by(a).by(model_llama).run()
    r = r.select("scenario.*", "agent.*", "answer.*", "prompt.*", "pick_comment", "pick_generated_tokens", "raw_model_response.pick_raw_model_response").to_pandas()
```

Could you please advise how I might resolve this? I’d prefer to continue running the experiments through EDSL if possible.

Thank you!

**Comment by rbyh** [comment]
Thanks for letting us know! Do you mind retrying? I reconfirmed we should be on the highest tier ("Build Tier 5" if you are looking at their billing page) but added plenty more credits to be safe.

Sorry about the inconvenience!

**Comment by KirillUtyashev** [comment]
Thank you for looking into this so quickly! Unfortunately, the issue still persists.

Just to rule out the possibility that the problem is on my side, I've attached a snippet of the code where I call Together AI's API directly:

```python
from together import Together
model_llama = Together(api_key=os.getenv('TOGETHER_API_KEY'))

for s in sl:
    job = q.by(s)
    a = Agent(...)
    r = job.by(a)
    prompts = r.show_prompts()
    user_prompt, system_prompt = prompts.data[0][0].text, prompts.data[0][1].text
    response = model_to_run.chat.completions.create(
        model="meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
        system_prompt=system_prompt,
        messages=[
            {
                "role": "system",
                "content": user_prompt
            }
        ],
        logprobs=True
    )
    generated_tokens = response.choices[0].message.content
    ...

**Comment by rbyh** [comment]
Apologies -- we had a key issue. It should be fixed now!

**Comment by KirillUtyashev** [comment]
Thank you for the quick update!

As I run the experiments now, the issue still seems to persist on my end. Should I do anything specific to update the package to reflect your changes? Perhaps I’m missing how to pull the latest version correctly? Please let me know if there’s anything I should do on my side to access the fix.

**Comment by zer0dss** [comment]
@KirillUtyashev It should work now. Thanks for letting us know.

**Comment by KirillUtyashev** [comment]
Everything works now, thank you very much!

**Comment by rbyh** [comment]
Thanks for your patience!
